//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServerListener.RepoLibraryReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/RepoLibrary")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Settings {
            get {
                return this.SettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingsField, value) != true)) {
                    this.SettingsField = value;
                    this.RaisePropertyChanged("Settings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RepoLibraryReference.IRepoLibrary")]
    public interface IRepoLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepoLibrary/GetProject", ReplyAction="http://tempuri.org/IRepoLibrary/GetProjectResponse")]
        ApplicationServerListener.RepoLibraryReference.Project GetProject(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepoLibrary/GetProject", ReplyAction="http://tempuri.org/IRepoLibrary/GetProjectResponse")]
        System.Threading.Tasks.Task<ApplicationServerListener.RepoLibraryReference.Project> GetProjectAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepoLibrary/SaveProject", ReplyAction="http://tempuri.org/IRepoLibrary/SaveProjectResponse")]
        string SaveProject(ApplicationServerListener.RepoLibraryReference.Project data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepoLibrary/SaveProject", ReplyAction="http://tempuri.org/IRepoLibrary/SaveProjectResponse")]
        System.Threading.Tasks.Task<string> SaveProjectAsync(ApplicationServerListener.RepoLibraryReference.Project data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepoLibraryChannel : ApplicationServerListener.RepoLibraryReference.IRepoLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepoLibraryClient : System.ServiceModel.ClientBase<ApplicationServerListener.RepoLibraryReference.IRepoLibrary>, ApplicationServerListener.RepoLibraryReference.IRepoLibrary {
        
        public RepoLibraryClient() {
        }
        
        public RepoLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepoLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepoLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepoLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationServerListener.RepoLibraryReference.Project GetProject(string name) {
            return base.Channel.GetProject(name);
        }
        
        public System.Threading.Tasks.Task<ApplicationServerListener.RepoLibraryReference.Project> GetProjectAsync(string name) {
            return base.Channel.GetProjectAsync(name);
        }
        
        public string SaveProject(ApplicationServerListener.RepoLibraryReference.Project data) {
            return base.Channel.SaveProject(data);
        }
        
        public System.Threading.Tasks.Task<string> SaveProjectAsync(ApplicationServerListener.RepoLibraryReference.Project data) {
            return base.Channel.SaveProjectAsync(data);
        }
    }
}
